src/Entity/Book.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Entity\Traits\DescriptionEntityTrait;
use App\Entity\Traits\QuantityEntityTrait;
use App\Entity\Traits\TitleEntityTrait;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity()
 * @ORM\Table(
 *     name="books"
 * )
 */
class Book extends AbstractEntity
{
    use TitleEntityTrait,
        DescriptionEntityTrait,
        QuantityEntityTrait;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Author", mappedBy="books")
     */
    protected Collection $authors;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Reading", mappedBy="book")
     */
    protected Collection $reading;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Order", mappedBy="book")
     */
    protected Collection $orders;

    public function __construct()
    {
        $this->authors = new ArrayCollection();
        $this->reading = new ArrayCollection();
        $this->orders = new ArrayCollection();
    }

    /**
     * @return Collection|Author[]
     */
    public function getAuthors(): Collection
    {
        return $this->authors;
    }

    public function addAuthor(Author $author): self
    {
        if (!$this->authors->contains($author)) {
            $this->authors[] = $author;
            $author->addBook($this);
        }

        return $this;
    }

    public function removeAuthor(Author $author): self
    {
        if ($this->authors->removeElement($author)) {
            $author->removeBook($this);
        }

        return $this;
    }

    /**
     * @return Collection|Reading[]
     */
    public function getReading(): Collection
    {
        return $this->reading;
    }

    public function addReading(Reading $reading): self
    {
        if (!$this->reading->contains($reading)) {
            $this->reading[] = $reading;
            $reading->setBook($this);
        }

        return $this;
    }

    public function removeReading(Reading $reading): self
    {
        if ($this->reading->removeElement($reading)) {
            // set the owning side to null (unless already changed)
            if ($reading->getBook() === $this) {
                $reading->setBook(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Order[]
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Order $order): self
    {
        if (!$this->orders->contains($order)) {
            $this->orders[] = $order;
            $order->setBook($this);
        }

        return $this;
    }

    public function removeOrder(Order $order): self
    {
        if ($this->orders->removeElement($order)) {
            // set the owning side to null (unless already changed)
            if ($order->getBook() === $this) {
                $order->setBook(null);
            }
        }

        return $this;
    }

}

src/Entity/User.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Entity\Contracts\UserInterface;
use App\Entity\Traits\ActiveEntityTrait;
use App\Entity\Traits\Contact\FirstNameEntityTrait;
use App\Entity\Traits\Contact\LastNameEntityTrait;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use function array_filter;
use function implode;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\Table(
 *     name="users",
 *     indexes={
 *          @ORM\Index(name="idx_active", columns={"active"}),
 *     }
 * )
 * @ORM\EntityListeners({"App\EventListener\Doctrine\UserEntityListener"})
 */
class User extends AbstractEntity implements UserInterface
{

    use FirstNameEntityTrait,
        LastNameEntityTrait,
        ActiveEntityTrait;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Reading", mappedBy="user")
     */
    protected Collection $reading;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Order", mappedBy="user")
     */
    protected Collection $orders;

    /**
     * @ORM\Column(name="username", type="string", length=60, nullable=false)
     */
    protected ?string $username = null;

    /**
     * @ORM\Column(name="password", type="string", length=64, nullable=false)
     */
    protected ?string $password = null;

    /**
     * @var null|string
     * not mapped property
     */
    protected ?string $plainPassword = null;

    /**
     * @ORM\Column(name="email", type="string", length=60, nullable=true)
     */
    protected ?string $email = null;

    /**
     * @ORM\Column(name="salt", type="string", nullable=false)
     */
    protected string $salt;

    /**
     * @ORM\Column(name="roles", type="json", nullable=false)
     */
    protected array $roles = [UserInterface::ROLE_USER];

    public function __toString(): string
    {
        $labels = [];
        if (!$this->getId()) {
            $labels[] = 'New User';
        } else {
            $labels[] = $this->getUsername();
            $labels[] = !$this->isActive() ? '(disabled)' : null;
        }

        return implode(' ', array_filter($labels));
    }

    public function __construct()
    {
        try {
            $this->salt = bin2hex(random_bytes(12));
        } catch (\Exception $e) {
            $this->salt = '';
        }
        $this->reading = new ArrayCollection();
        $this->orders = new ArrayCollection();
    }

    public function isAdmin(): bool
    {
        return $this->hasRole(self::ROLE_ADMIN);
    }

    public function isLibrarian(): bool
    {
        return $this->isAdmin() || $this->hasRole(self::ROLE_LIBRARIAN);
    }

    public function isUser(): bool
    {
        return (bool)$this->getId();
    }

    public function isReader(): bool
    {
        return $this->isUser() || $this->hasRole(self::ROLE_READER);
    }

    public function getUsername(): string
    {
        return (string)$this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getPlainPassword(): ?string
    {
        return $this->plainPassword;
    }

    public function setPlainPassword(?string $plainPassword): self
    {
        $this->plainPassword = $plainPassword;

        if ($plainPassword) {
            //$this->setUpdatedAt(new DateTime());
        }

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getSalt(): string
    {
        return $this->salt;
    }

    public function setSalt(string $salt): self
    {
        $this->salt = $salt;

        return $this;
    }

    public function getRoles(): array
    {
        return $this->roles;
    }

    public function hasRole(string $role): bool
    {
        return in_array($role, $this->getRoles(), true);
    }

    public function getRole(): ?string
    {
        return $this->roles[0] ?? '';
    }

    public function eraseCredentials()
    {
    }

    public function serialize(): ?string
    {
        return serialize(
            [
                $this->id,
                $this->username,
                $this->password,
                $this->salt,
            ]
        );
    }

    public function unserialize($serialized): void
    {
        [
            $this->id,
            $this->username,
            $this->password,
            $this->salt,
        ] = unserialize($serialized, ['allowed_classes' => [self::class]]);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @return Collection|Reading[]
     */
    public function getReading(): Collection
    {
        return $this->reading;
    }

    public function addReading(Reading $reading): self
    {
        if (!$this->reading->contains($reading)) {
            $this->reading[] = $reading;
            $reading->setUser($this);
        }

        return $this;
    }

    public function removeReading(Reading $reading): self
    {
        if ($this->reading->removeElement($reading)) {
            // set the owning side to null (unless already changed)
            if ($reading->getUser() === $this) {
                $reading->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Order[]
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Order $order): self
    {
        if (!$this->orders->contains($order)) {
            $this->orders[] = $order;
            $order->setUser($this);
        }

        return $this;
    }

    public function removeOrder(Order $order): self
    {
        if ($this->orders->removeElement($order)) {
            // set the owning side to null (unless already changed)
            if ($order->getUser() === $this) {
                $order->setUser(null);
            }
        }

        return $this;
    }

}

src/Form/Type/BookType.php
<?php
declare(strict_types=1);

namespace App\Form\Type;

use App\Service\Manager\AuthorManager;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Validator\Constraints\GreaterThanOrEqual;
use Symfony\Component\Validator\Constraints\NotBlank;

class BookType extends AbstractEntityType
{

    protected AuthorManager $authorManager;

    public function __construct(AuthorManager $authorManager)
    {
        $this->authorManager = $authorManager;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add(
                'title',
                TextType::class,
                [
                    'constraints' => new NotBlank()
                ]
            )
            ->add(
                'description',
                TextareaType::class
            )
            ->add(
                'authors',
                ChoiceType::class,
                [
                    'multiple' => true,
                    'choices'  => $this->resolveAuthorsChoices(),
                ]
            )
            ->add(
                'quantity',
                NumberType::class,
                [
                    'empty_data'  => 1,
                    'scale'       => 0,
                    'constraints' => [
                        new GreaterThanOrEqual(['value' => 0])
                    ]
                ]
            );
    }

    protected function resolveAuthorsChoices(): array
    {
        $choices = [];
        $authors = $this->authorManager->all();
        foreach ($authors as $author) {
            $choices[$author['first_name'] . ' ' . $author['last_name']] = (int)$author['id'];
        }

        return $choices;
    }
}

src/Controller/BookController.php
<?php
declare(strict_types=1);

namespace App\Controller;

use App\Form\Type\BookType;
use App\Form\Type\OrderBookType;
use App\Service\Manager\BookManager;
use App\Service\Manager\ReadingManager;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route(path="/book")
 */
class BookController extends AbstractController
{

    protected BookManager    $bookManager;
    protected ReadingManager $readerManager;

    public function __construct(
        BookManager $bookManager,
        ReadingManager $readingManager
    ) {
        $this->bookManager   = $bookManager;
        $this->readerManager = $readingManager;
    }

    /**
     * @Route(path="/list", name="book.list")
     */
    public function index(Request $request): Response
    {
        $filter = $request->query->all();
        $books  = $this->bookManager->paginate($filter);

        return $this->render('default/book/index.html.twig',
            [
                'books'         => $books,
                'bookManager'   => $this->bookManager,
                'readerManager' => $this->readerManager,
            ]
        );
    }

    /**
     * @Route(path="/add", name="book.add")
     */
    public function add(Request $request): Response
    {
        $form = $this->bookManager->form(BookType::class);
        if ($request->isMethod(Request::METHOD_POST) &&
            !($errors = $this->bookManager->handleForm($form, $request))
        ) {
            $data = $form->getData();
            $this->bookManager->create($data);

            return $this->redirectToRoute('book.list');
        }

        return $this->render(
            'default/book/add.html.twig',
            [
                'form' => $form->createView(),
            ]
        );
    }

    /**
     * @Route(path="/{id}/edit", name="book.edit")
     */
    public function edit(Request $request, int $id): Response
    {
        $data            = $this->bookManager->get($id);
        $data['authors'] = !empty($data['authors']) ? array_keys($data['authors']) : [];
        $form            = $this->bookManager->form(BookType::class, $data ?? [], ['id' => $id]);
        if ($request->isMethod(Request::METHOD_POST) &&
            !($errors = $this->bookManager->handleForm($form, $request))
        ) {
            $data = $form->getData();
            $this->bookManager->update($id, $data);

            return $this->redirectToRoute('book.list');
        }

        return $this->render(
            'default/book/edit.html.twig',
            [
                'id'   => $id,
                'form' => $form->createView(),
            ]
        );
    }

    /**
     * @Route(path="/{id}/delete", name="book.delete")
     */
    public function delete(int $id): Response
    {
        $this->bookManager->delete($id);

        return $this->redirectToRoute('book.list');
    }

    /**
     * @Route(path="/{id}/order", name="book.order")
     */
    public function order(Request $request, int $id): Response
    {
        $userId = $this->getUser() ? $this->getUser()->getId() : null;
        $book   = $this->bookManager->get($id);
        $form   = $this->bookManager->form(OrderBookType::class, [], ['book_id' => $id, 'user_id' => $userId]);
        if ($request->isMethod(Request::METHOD_POST) &&
            !($errors = $this->bookManager->handleForm($form, $request))
        ) {
            $data = $form->getData();
            $this->bookManager->order($data);

            return $this->redirectToRoute('book.list');
        }

        return $this->render(
            'default/book/order.html.twig',
            [
                'id'   => $id,
                'book' => $book,
                'form' => $form->createView(),
            ]
        );
    }
}

src/Controller/DefaultController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;

class DefaultController extends AbstractController
{
    /**
     * @Route(path="/", name="homepage")
     */
    public function index(): Response
    {
        $user = $this->getUser();

        if ($user) {
            switch (true) {
                case $user->isAdmin():
                    return $this->redirectToRoute('admin.list');

                case $user->isLibrarian():
                    return $this->redirectToRoute('order.list');

                case $user->isReader():
                    return $this->redirectToRoute('book.list');

            }

            return $this->redirectToRoute('profile');
        }

        return $this->render('default/homepage.html.twig');
    }

    public function cms(Request $request, string $slug): Response
    {
        throw new NotFoundHttpException();
    }
}

templates/default/book/add.html.twig
{% extends 'layout.main.html.twig' %}


{% block breadcrumbs %}
    {% set breadcrumbs = [
        {'url': path('book.list'), 'title': 'Books'},
        {'url': path('book.add'), 'title': 'Add', 'active': true},
    ] %}
    {{ parent() }}
{% endblock %}

{% block content %}

    <form action="{{ path('book.add') }}" method="post" novalidate="novalidate">
        {{ form_rest(form) }}
        <button type="submit" class="btn btn-info">Submit</button>
    </form>
{% endblock %}

templates/default/book/edit.html.twig
{% extends 'layout.main.html.twig' %}


{% block breadcrumbs %}
    {% set breadcrumbs = [
        {'url': path('book.list'), 'title': 'Books'},
        {'url': path('book.edit', {'id': id}), 'title': 'Edit', 'active': true},
    ] %}
    {{ parent() }}
{% endblock %}

{% block content %}

    <form action="{{ path('book.edit', {'id': id}) }}" method="post" novalidate="novalidate">
        {{ form_rest(form) }}
        <button type="submit" class="btn btn-info">Submit</button>
    </form>
{% endblock %}

templates/default/book/index.html.twig
{% extends 'layout.main.html.twig' %}
{# @var \App\Service\Manager\BookManager bookManager #}
{# @var \App\Service\Manager\ReadingManager reradingManager #}


{% block breadcrumbs %}
    {% set breadcrumbs = [
        {'url': path('book.list'), 'title': 'Books', 'active': true},
    ] %}
    {{ parent() }}
{% endblock %}

{% block content %}
    {% if app.user and app.user.librarian %}
        <a href="{{ path('book.add') }}" class="btn btn-info mb-2">Add</a>
    {% endif %}
    <div class="float-right mb-2 mr-2">
        {% include 'default/_partials/search-form.html.twig' with {'action': path('book.list') } %}
    </div>

    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Title</th>
            <th scope="col">Description</th>
            <th scope="col">Author</th>
            {% if app.user and app.user.librarian %}
                <th scope="col">Quantity</th>
                <th scope="col">Reads</th>
            {% endif %}

            {% if app.user %}
                <th scope="col">Actions</th>
            {% endif %}
        </tr>
        </thead>
        <tbody>

        {% for book in books %}
            {% set countReadBooks = readerManager.countBooks(book.id) %}
            {% set showOrderButton = countReadBooks < book.quantity %}

            <tr>
                <th scope="row">{{ book.id }}</th>
                <td>{{ book.title }}</td>
                <td>{{ book.description }}</td>
                <td>
                    {% set authors = bookManager.authors(book.id) %}
                    {% for author in authors %}
                        {{ author.first_name }} {{ author.last_name }} <br/>
                    {% endfor %}
                </td>
                {% if app.user and app.user.librarian %}
                    <td>{{ book.quantity }}</td>
                    <td>{{ countReadBooks }}</td>
                {% endif %}

                {% if app.user %}
                    <td>
                        {% if showOrderButton %}
                            <a href="{{ path('book.order', {'id': book.id}) }}" class="btn btn-success">Order</a>
                        {% endif %}

                        {% if app.user and app.user.librarian %}
                            <a href="{{ path('book.edit', {'id': book.id}) }}" class="btn btn-info">Edit</a>
                            <a href="{{ path('book.delete', {'id': book.id}) }}" class="btn btn-danger">Delete</a>
                        {% endif %}
                    </td>
                {% endif %}
            </tr>
        {% endfor %}

        </tbody>
    </table>
    <div class="pagination">
        {{ knp_pagination_render(books) }}
    </div>
{% endblock %}

templates/default/book/order.html.twig
{% extends 'layout.main.html.twig' %}


{% block breadcrumbs %}
    {% set breadcrumbs = [
        {'url': path('book.list'), 'title': 'Books'},
        {'url': path('book.order', {'id': id}), 'title': 'Order', 'active': true},
    ] %}
    {{ parent() }}
{% endblock %}

{% block content %}

    <form action="{{ path('book.order', {'id': id}) }}" method="post" novalidate="novalidate">

        <div class="form-group">
            <label>Book</label>
            <p>{{ book.title }}</p>
        </div>

        <div class="form-group">
            <label>Authors</label>
            <p>
                {% for author in book.authors %}
                    {{ author.first_name }} {{ author.last_name }}
                    {{ loop.last == false ? ', ' : null }}
                {% endfor %}
            </p>
        </div>

        {{ form_rest(form) }}
        <button type="submit" class="btn btn-info">Submit</button>
    </form>

{% endblock %}